### ISSUE TITLE
USER STORY: Player customize game board 

### ISSUE THREAD

**Issue by ObiOne84** [ObiOne84/battleship-game#1]
As a **player** I can **quickly identify my game board** so that **I know the position of my ships**

## Acceptance Criteria:
- Create a function to accept username
- Pass the username to the game board
- Personalise feedback messages with username

## Tasks:
- [x] Function that accepts alphabetic letters as a user input
- [x] Restric user input to a maximum of 10 letters and a minimum of 3 characters
- [x] Validate user input
- [x] Pass the username to the game board
- [x] Pass the username to feedback messages
- [x] Test the code
- [x] Document in the readme file

**Comment by ObiOne84** [comment]
All task completed.
