### ISSUE TITLE
USER STORY: User can play classic Battleship game on computer

### ISSUE THREAD

**Issue by ObiOne84** [ObiOne84/battleship-game#2]
As a **User**, I can **play Battleship game on my computer as I used to do playing with pen and paper** so that **I can relive great memories of my childhood and have a fun time**

## Acceptance Criteria:
- The game board should remind the paper version with numbered columns and row names as letters
- The user should be able to place their ships on the game board by passing coordinates within the board size
- The user should be able to shoot at the computer ships using coordinates in form A1, B2 etc., within the board size
- The computer should be randomly guessing the position of the user's ships within the board size
- The game score is recorded after each round and displayed to the user as a table
- The miss shots are marked with "0", hits with "X", and ships marked as "S."
- The user should not be able to see computer ships
- The user should be able to see hits and misses against the computer board
- The user should be able to see their game board

## Tasks:
- [x] Create a Python class of GameBoard to hold game boards, ships, and user guesses
- [x] Create a class method to print the user and computer game boards
- [x] Create a class method to allow users to add ships to the board
- [x] Create a class method to add ships to the board randomly
- [x] Create a class method to allow users to guess against the board
- [x] Create a class method to generate random guesses against the user board
- [x] Add validation for user input
- [x] Create a function to calculate the game score and print it to terminal
- [x] Test the code
- [x] Document in the readme

**Comment by ObiOne84** [comment]
All tasks completed, code validated and tested.
