### ISSUE TITLE
USER STORY: User can choose the game level

### ISSUE THREAD

**Issue by ObiOne84** [ObiOne84/battleship-game#3]
As a **player**, I can **choose the game level that matches my skills** so that **I can get familiar with the game interface and gradually improve my gaming skills**

## Acceptance Criteria:
- The game should have offered three difficulty levels - beginner, intermediate and expert.
- Beginner level should set the game on the board size 5 x 5, with 5 ships and 25 shots.
- Intermediate level should set the game on a 10 x 10 board with 10 ships and 75 shots.
- Expert level should build 10 x 10 grid, 20 ships and allow 50 shots.

## Tasks:
- [x] Create a function to collect user input to choose the game level and set game parameters
- [x] Validate user input
- [x] Test the code
- [x] Document in readme

**Comment by ObiOne84** [comment]
All tasks completed.
