### ISSUE TITLE
USER STORY: User can read game rules

### ISSUE THREAD

**Issue by ObiOne84** [ObiOne84/battleship-game#4]
As a **user**, I can **read and understand the game rules** so that **I know how to play the game**

## Acceptance Criteria:
- User can clearly understand the game's purpose
- User can understand the difference between each level
- User can understand the game markings

## Tasks:
- [x] Create a game logo using ASCII art
- [x] Print game description to terminal
- [x] Print a description of each game level to terminal
- [x] Print game marking and rules to terminal

**Comment by ObiOne84** [comment]
All tasks resolved.
